try:
    ret=12/n
except:
    print("some exception happened")
else:
    print("result:",ret)
